[package]
name = "repositories"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
lazy_static = "^1.4"
async_once = "^0.2"
sqlx = { version = "^0.8", features = ["postgres", "runtime-tokio", "tls-native-tls"] }
environment = { path = "../environment" }
types = { path = "../types" }
anyhow = "^1.0"
tokio = { version = "^1.37", features = ["rt-multi-thread", "macros"] }
tracing = "^0.1"