name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ## Disabled for lack of support for latest version of Rust
  # lint-test:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Lint
  #     run: make lint
  #   - name: Run tests
  #     run: make test